name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.5-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ran tests
        run: mvn clean test
