name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.5-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ran tests
        run: mvn clean tests
